export const NOTES = {
	DELETE_ALL: 'DELETE_ALL',
	ARCHIVE_ALL: 'ARCHIVE_ALL',
	EDIT_ID: 'EDIT_ID',
	ARCHIVE_ID: 'ARCHIVE_ID',
	DELETE_ID: 'DELETE_ID',
	CANCEL_ID: 'CANCEL_ID',
	SAVE_ID: 'SAVE_ID',
};
